name: Nightly Update
on:
  schedule:
    - cron: '0 16 * * *'
  workflow_dispatch:
jobs:
  run-scripts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v6
        with:
          python-version: '3.x'
      - name: Run scripts
        run: |
          python geosite-extractor.py -c category-ru -o raw/domain_list_extracted.txt
          bash merge-and-sort.sh
          bash generate-domain-rules.sh
          bash generate-ip-geo-detect-rules.sh
      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git diff --staged --quiet || git commit -m "Automated update: $(date +'%Y-%m-%d')"
          git push
      - name: Set release tag
        run: echo "RELEASE_TAG=release-$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.RELEASE_TAG }}
          name: "${{ env.RELEASE_TAG }}"
          files: |
            output/ru-unbound-domain-whitelist.conf
            output/ru-unbound-domain-blocklist.conf
            output/ru-domain.list
            output/ip-geo-detect-domain.list
