name: Nightly Update
on:
  schedule:
    - cron: '0 16 * * *'
  workflow_dispatch:
jobs:
  run-scripts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v6
        with:
          python-version: '3.x'
      - name: Run scripts
        run: |
          python extract-domains.py
          bash merge-and-sort.sh
          bash generate-domain-rules.sh
          bash generate-ip-geo-detect-rules.sh
      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git diff --staged --quiet || git commit -m "Automated update: $(date +'%Y-%m-%d')"
          git push
      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: "release-$(date +'%Y-%m-%d')"
          name: "Automated nightly release $(date +'%Y-%m-%d')"
          files: |
            output/ru-unbound-domain-blocklist.conf
            output/ru-foreign-TLD-domain.list
            output/ip-geo-detect-domain.list
